apiVersion: v1
kind: Service
metadata:
  name: {{ include "remote-config-system.fullname" . }}-demo-app
  labels:
    {{- include "remote-config-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: demo-app
spec:
  type: {{ .Values.demoApp.service.type | default .Values.global.serviceType }}
  ports:
    - port: {{ .Values.demoApp.service.port }}
      targetPort: {{ .Values.demoApp.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "remote-config-system.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: demo-app
