{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "remote-config-system.fullname" . }}-postgresql
  labels:
    {{- include "remote-config-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.targetPort }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "remote-config-system.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
