{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "remote-config-system.fullname" . }}-redis
  labels:
    {{- include "remote-config-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
      protocol: TCP
      name: redis
  selector:
    {{- include "remote-config-system.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
