apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote-config-system
  namespace: argocd
  labels:
    app.kubernetes.io/name: remote-config-system
    app.kubernetes.io/part-of: remote-config-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/loiu92/demo-remote-config-system.git
    targetRevision: main
    path: helm/remote-config-system
    helm:
      values: |
        api:
          image:
            tag: "main-165217b"
        demoApp:
          image:
            tag: "main-165217b"
        dashboard:
          image:
            tag: "main-165217b"
  destination:
    server: https://kubernetes.default.svc
    namespace: remote-config-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
