# Default values for remote-config-system
# This is a YAML-formatted file.

# Global settings
global:
  imageRegistry: "ghcr.io"
  imagePullSecrets: []

# API Service Configuration
api:
  image:
    repository: ghcr.io/loiu92/demo-remote-config-system/api
    tag: "latest"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  service:
    type: LoadBalancer  # Direct access to API
    port: 8080
    targetPort: 8080
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  env:
    GIN_MODE: release
  
  healthCheck:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5

# Demo App Configuration (React)
demoApp:
  image:
    repository: ghcr.io/loiu92/demo-remote-config-system/demo-app
    tag: "latest"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  service:
    type: LoadBalancer  # Direct access to demo app
    port: 3000
    targetPort: 3000
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  healthCheck:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5

  # Nginx configuration for API proxy
  nginx:
    # These values are automatically set by the Helm chart
    # but can be overridden if needed
    apiServiceName: ""  # Defaults to {{ include "remote-config-system.fullname" . }}-api
    apiServicePort: ""  # Defaults to {{ .Values.api.service.port }}

# Dashboard Configuration
dashboard:
  image:
    repository: ghcr.io/loiu92/demo-remote-config-system/dashboard
    tag: "latest"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  service:
    type: LoadBalancer  # Direct access to dashboard
    port: 4000
    targetPort: 4000
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  healthCheck:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5

  # Nginx configuration for API proxy
  nginx:
    # These values are automatically set by the Helm chart
    # but can be overridden if needed
    apiServiceName: ""  # Defaults to {{ include "remote-config-system.fullname" . }}-api
    apiServicePort: ""  # Defaults to {{ .Values.api.service.port }}

# PostgreSQL Configuration
postgresql:
  enabled: true
  # Use StatefulSet instead of Deployment for better data persistence
  useStatefulSet: true
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent

  replicaCount: 1
  
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  
  auth:
    database: remote_config
    username: postgres
    password: postgres
  
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""
    # Use subPath to avoid lost+found directory issues
    subPath: "pgdata"
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  healthCheck:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5

# Redis Configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379
  
  persistence:
    enabled: true
    size: 4Gi
    storageClass: ""
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  healthCheck:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5

# Nginx reverse proxy removed - each service has direct LoadBalancer access

# Ingress Configuration (routes to API service)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: remote-config-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod Security Context
podSecurityContext:
  fsGroup: 1001

# Security Context (default for most services)
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  capabilities:
    drop:
    - ALL

# PostgreSQL specific security context
postgresqlSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 999  # postgres user
  runAsGroup: 999 # postgres group
  capabilities:
    drop:
    - ALL

# PostgreSQL Pod Security Context
postgresqlPodSecurityContext:
  fsGroup: 999

# Node Selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
